version: '3'
services:
    nginx:
        build: ./../../http/nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
        ulimits:
            nproc: 819200
            nofile: 819200
    mysql:
        build:  ./../../db/mysql
        container_name: mysql
        command: --disable-log-app --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: root
    php:
        build:  ../../php/roadrunner
        container_name: php
        volumes:
            - ./rr.yaml:/roadrunner/rr.yaml:ro
            - ./app:/var/www/html:ro
        depends_on:
            - mysql
        environment:
            TIMEZONE: Europe/Moscow
            DATABASE: "mysql://root:root@mysql/app"
